(function(){
  'use strict';
  var STORE={currency:'ZAR',cartKey:'site_ecommerce_cart_v1'};
  var products=[];
  var money=new Intl.NumberFormat('en-ZA',{style:'currency',currency:STORE.currency});
  function price(value){return money.format(value/100);}
  function getCart(){try{return JSON.parse(localStorage.getItem(STORE.cartKey)||'[]');}catch(error){return [];}}
  function saveCart(cart){localStorage.setItem(STORE.cartKey,JSON.stringify(cart));updateCartCount();}
  function cartCount(){return getCart().reduce(function(total,item){return total+item.quantity;},0);}
  function updateCartCount(){document.querySelectorAll('[data-cart-count]').forEach(function(element){element.textContent=cartCount();element.hidden=cartCount()===0;});}
  function announce(message){var note=document.createElement('div');note.className='shop-message';note.setAttribute('role','status');note.textContent=message;document.body.appendChild(note);window.setTimeout(function(){note.remove();},2600);}
  function findProduct(id){return products.find(function(product){return product.id===id;});}
  function addToCart(id,quantity){var product=findProduct(id);if(!product||!product.inStock){return;}var cart=getCart();var item=cart.find(function(entry){return entry.id===id;});if(item){item.quantity+=quantity;}else{cart.push({id:id,quantity:quantity});}saveCart(cart);announce(product.name+' added to your cart.');}
  function updateQuantity(id,quantity){var cart=getCart();var item=cart.find(function(entry){return entry.id===id;});if(!item){return;}item.quantity=Math.max(0,Number(quantity)||0);saveCart(cart.filter(function(entry){return entry.quantity>0;}));}
  function removeItem(id){saveCart(getCart().filter(function(entry){return entry.id!==id;}));announce('Item removed from your cart.');}
  function productCard(product){return '<article class="shop-card"><a href="product.html?id='+encodeURIComponent(product.id)+'"><img class="shop-card-image" src="'+product.image+'" alt="'+product.name+'"></a><div class="shop-card-body"><span class="shop-card-category">'+product.category+'</span><h2><a href="product.html?id='+encodeURIComponent(product.id)+'">'+product.name+'</a></h2><p class="shop-card-description">'+product.description+'</p><div class="shop-card-bottom"><span class="shop-price">'+price(product.price)+'</span><div class="shop-card-actions"><a class="detail-link" href="product.html?id='+encodeURIComponent(product.id)+'">View</a><button class="button button-dark" type="button" data-add="'+product.id+'" '+(product.inStock?'':'disabled')+'>'+ (product.inStock?'Add':'Unavailable')+'</button></div></div></div></article>';}
  function renderShop(){var grid=document.querySelector('[data-product-grid]');if(!grid){return;}var search=(document.querySelector('[data-search]').value||'').toLowerCase().trim();var category=document.querySelector('[data-category]').value;var sort=document.querySelector('[data-sort]').value;var filtered=products.filter(function(product){return (!search||(product.name+' '+product.description).toLowerCase().indexOf(search)!==-1)&&(!category||product.category===category);});filtered.sort(function(a,b){if(sort==='price-low'){return a.price-b.price;}if(sort==='price-high'){return b.price-a.price;}return a.name.localeCompare(b.name);});document.querySelector('[data-shop-status]').textContent=filtered.length+' '+(filtered.length===1?'product':'products')+' shown';grid.innerHTML=filtered.length?filtered.map(productCard).join(''):'<div class="shop-empty"><h2>Nothing found yet.</h2><p>Try a different search or clear the filters to see the full collection.</p></div>';}
  function renderDetail(){var target=document.querySelector('[data-product-detail]');if(!target){return;}var product=findProduct(new URLSearchParams(window.location.search).get('id'));if(!product){target.innerHTML='<div class="shop-empty"><h1>Product not found</h1><p>That little thing may have wandered off.</p><a class="button button-dark" href="index.html">Back to the shop</a></div>';return;}document.title=product.name+' | Hasies en Gansies';target.innerHTML='<div><img class="product-detail-image" src="'+product.image+'" alt="'+product.name+'"></div><div class="detail-copy"><span class="detail-category">'+product.category+'</span><h1>'+product.name+'</h1><p class="detail-description">'+product.description+'</p><p class="detail-price">'+price(product.price)+'</p><p class="detail-stock">'+(product.inStock?'In stock - ready to enquire':'Currently unavailable')+'</p><div class="quantity-row"><label class="quantity-label" for="detail-quantity">Quantity</label><input class="quantity-input" id="detail-quantity" type="number" min="1" value="1" '+(product.inStock?'':'disabled')+'></div><button class="button button-dark" type="button" data-add="'+product.id+'" '+(product.inStock?'':'disabled')+'>'+(product.inStock?'Add to cart':'Unavailable')+' <span aria-hidden="true">↗</span></button></div>';}
  function renderCart(){var target=document.querySelector('[data-cart-content]');if(!target){return;}var items=getCart().map(function(item){return {item:item,product:findProduct(item.id)};}).filter(function(entry){return entry.product;});if(!items.length){target.innerHTML='<div class="cart-empty"><h1>Your cart is quiet.</h1><p>Add something lovely and it will appear here.</p><a class="button button-dark" href="index.html">Browse the shop <span aria-hidden="true">↗</span></a></div>';return;}var subtotal=items.reduce(function(total,entry){return total+entry.product.price*entry.item.quantity;},0);target.innerHTML='<div class="cart-list">'+items.map(function(entry){var product=entry.product;return '<article class="cart-item"><img class="cart-item-image" src="'+product.image+'" alt="'+product.name+'"><div><h2>'+product.name+'</h2><p>'+product.category+'</p></div><span class="cart-item-price">'+price(product.price)+'</span><div class="quantity-controls"><button class="quantity-button" type="button" data-decrease="'+product.id+'" aria-label="Decrease '+product.name+' quantity">-</button><label class="sr-only" for="quantity-'+product.id+'">Quantity for '+product.name+'</label><input class="quantity-input quantity-input--cart" id="quantity-'+product.id+'" type="number" min="0" value="'+entry.item.quantity+'" data-quantity="'+product.id+'"><button class="quantity-button" type="button" data-increase="'+product.id+'" aria-label="Increase '+product.name+' quantity">+</button></div><button class="remove-button" type="button" data-remove="'+product.id+'">Remove</button></article>';}).join('')+'</div><aside class="cart-summary"><h2>Order summary</h2><div class="summary-row"><span>Subtotal</span><strong>'+price(subtotal)+'</strong></div><div class="summary-row summary-total"><span>Total</span><strong>'+price(subtotal)+'</strong></div><a class="button button-dark" href="../contact.html?order='+encodeURIComponent(items.map(function(entry){return entry.product.name+' x'+entry.item.quantity;}).join(', '))+'">Request this order <span aria-hidden="true">↗</span></a><button class="reset-button" type="button" data-clear-cart>Clear cart</button><p class="cart-note">Online payment is not connected yet. This enquiry sends your selected items to Hasies en Gansies so the order can be confirmed personally.</p></aside>';
  }
  function init(){fetch('data/products.json').then(function(response){if(!response.ok){throw new Error('Product data could not be loaded.');}return response.json();}).then(function(data){products=data;updateCartCount();renderShop();renderDetail();renderCart();}).catch(function(error){console.error(error);document.querySelectorAll('.loading-state').forEach(function(element){element.textContent='The shop is taking a little longer to load. Please refresh and try again.';});});}
  document.addEventListener('click',function(event){var add=event.target.closest('[data-add]');if(add){var detailQuantity=document.getElementById('detail-quantity');addToCart(add.dataset.add,detailQuantity?Math.max(1,Number(detailQuantity.value)||1):1);return;}var increase=event.target.closest('[data-increase]');if(increase){var item=getCart().find(function(entry){return entry.id===increase.dataset.increase;});updateQuantity(increase.dataset.increase,(item?item.quantity:0)+1);renderCart();return;}var decrease=event.target.closest('[data-decrease]');if(decrease){var itemToDecrease=getCart().find(function(entry){return entry.id===decrease.dataset.decrease;});updateQuantity(decrease.dataset.decrease,(itemToDecrease?itemToDecrease.quantity:1)-1);renderCart();return;}var remove=event.target.closest('[data-remove]');if(remove){removeItem(remove.dataset.remove);renderCart();return;}if(event.target.closest('[data-clear-cart]')){saveCart([]);renderCart();announce('Your cart has been cleared.');}});
  document.addEventListener('input',function(event){if(event.target.matches('[data-quantity]')){updateQuantity(event.target.dataset.quantity,event.target.value);renderCart();}});
  document.addEventListener('change',function(event){if(event.target.matches('[data-search], [data-category], [data-sort]')){renderShop();}});
  document.addEventListener('DOMContentLoaded',function(){updateCartCount();var search=document.querySelector('[data-search]');var category=document.querySelector('[data-category]');var reset=document.querySelector('[data-reset]');var requestedCategory=new URLSearchParams(window.location.search).get('category');if(category&&requestedCategory){category.value=requestedCategory;}if(search){search.addEventListener('input',renderShop);}if(reset){reset.addEventListener('click',function(){document.querySelector('[data-search]').value='';document.querySelector('[data-category]').value='';document.querySelector('[data-sort]').value='name';renderShop();});}init();});
})();
